/* GWBasic Interpreter Types */

#ifndef _GWBASIC_INTERPRETER_TYPES_H_
#define _GwBASIC_INTERPRETER_TYPES_H_

#define GWB_DIRECT_MODE_TYPE		1000	
#define GWB_COMMAND_TYPE		1001
#define GWB_STATEMENT_TYPE		1002
#define GWB_FUNCTION_TYPE		1003

#endif
