/* GWBasic Interpreter Types */

#ifndef _GWBASIC_INTERPRETER_TYPES_H_
#define _GwBASIC_INTERPRETER_TYPES_H_

#define GWBNT_DIRECT_MODE		1000	
#define GWBNT_INDIRECT_MODE		1001
#define GWBNT_COMMAND			1003
#define GWBNT_STATEMENT			1004
#define GWBNT_FUNCTION			1005

#endif
