/* GWBasic Graphical settings */

#ifndef _GWBG_SETTINGS_H_
#define _GWBG_SETTINGS_H_

/* LATER IT WILL BE MOVED INTO CONFIG FILE */

#define GWBGS_SCREEN9W		640
#define GWBGS_SCREEN9H 		480

#define GWBGS_TEXTBUFFER_LINES		34
#define GWBGS_TEXTBUFFER_COLUMNS	70
#define GWBGS_TEXTBUFFER_LINEDISTANCE	13


#define GWBGS_DISPLAYWIDTH	GWBGS_SCREEN9W	
#define GWBGS_DISPLAYHEIGHT 	GWBGS_SCREEN9H

#endif
