/* GWBasic Graphical settings */

#ifndef _GWBG_SETTINGS_H_
#define _GWBG_SETTINGS_H_

/* LATER IT WILL BE MOVED INTO CONFIG FILE */

#define GWBG_SETTINGS_SCREEN_9_WIDTH		320
#define GWBG_SETTINGS_SCREEN_9_HEIGHT 		240

#define GWBGS_DISPLAY_WIDTH			320
#define GWBGS_DISPLAY_HEIGHT 			240

#endif
